# Generated by Django 4.2.13 on 2026-06-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_hod',
            field=models.BooleanField(default=False),
        ),
    ]
